apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: mainpage
  labels:
    app: test
  name: test
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: nginx
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: mainpage
          subPath: index.html
      volumes:
      - name: mainpage
        configMap:
          name: mainpage
