{{- range .Values.teams }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-role
  namespace: {{ . }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get
---
{{- end }}
